CREATE DATABASE streaming;

USE streaming;

CREATE TABLE USUARIO (
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    ENDERECO VARCHAR(250),
    SENHA VARCHAR(10)
);

CREATE TABLE VIDEO (
	ID_VIDEO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50),
    EPISODIO INT,
    CATEGORIA VARCHAR(25),
    PRODUTORA VARCHAR(25),
    ANO INT NOT NULL,
    DURACAO INT NOT NULL
);

CREATE TABLE ATOR (
	ID_ATOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150),
    LOCAL_NASCIMENTO VARCHAR(100),
    DATA_NASCIMENTO DATE
);

CREATE TABLE MENSALIDADE (
	ID_MENSALIDADE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGAMENTO DECIMAL NOT NULL,
    CONSTRAINT PK_MENSALIDADE_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE AVALIACAO (
	ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_VIDEO INT NOT NULL,
    NOTA VARCHAR(2),
    CONSTRAINT PK_AVALIACAO_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT PK_AVALIACAO_FILME FOREIGN KEY(ID_VIDEO) REFERENCES VIDEO (ID_VIDEO)
);

ALTER TABLE MENSALIDADE ADD RECORRENCIA VARCHAR(10);
ALTER TABLE AVALIACAO DROP COLUMN NOTA;
ALTER TABLE AVALIACAO ADD NOTA INT;